#include <iostream>
#include <time.h> // time
#include <random> //random

int randomGen10()
{
	std::random_device rd;  //Will be used to obtain a seed for the random number engine
	std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
	std::uniform_int_distribution<> distrib(1, 10); // Here is where you can change the MIN and MAX values of the random dib.

	for (int n = 0; n < 10; ++n)
		//Use `distrib` to transform the random unsigned int generated by gen into an int in [1, 10]

		int randResult;
	int randResult = distrib(gen);
	return randResult;
}

int randomGen100()
{
	std::random_device rd;  //Will be used to obtain a seed for the random number engine
	std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
	std::uniform_int_distribution<> distrib(1, 100);

	for (int n = 0; n < 10; ++n)

		int randResult;
	int randResult = distrib(gen);
	return randResult;
}

void clearScreen()
{
	system("cls");
}